<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>The Free Intellectual.com</title>
<?

	if ($this->dojo()->isEnabled())
	{
		$this->dojo()->addStyleSheetModule('dijit.themes.claro');
	    echo $this->dojo();
	}
?>

<style>
*
{
Margin: 0;
Padding: 0;
}
HTML
{
Height: 100%;
}
BODY
{
	Height: 100%;
}



</style>
<?php echo $this->jQuery?>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/themes/base/jquery-ui.css"/>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js" /></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.js"></script>
</head>

<body class="claro">

<?php echo $this->Render("User_Interface.phtml");?>
<?php echo $this->dojo();?>
</body>

</html>
