<?php
	// Zend Dojo
	echo $this->borderContainer//()->captureStart
	(
   		"User_Interface",
		$this->render("Header.phtml")
		.
		$this->render("Left.phtml")
		.
		$this->render("Center.phtml")
		.
		$this->render("Right.phtml")
		.
		$this->render("Footer.phtml"),
		array
		(
			"splitter" => "true",
			"style" => "width:100%;height:100%; border: 0;"
		)
	);
?>



<?php // $this->borderContainer()->captureEnd()?>